app:
  name: UpGo
  debug: false
  version: v1.0.4
  owner: ozeer
  repo: upgo
  install_dir: /usr/local/bin
log:
  MaxSize: 1
  MaxBackups: 10
  MaxAge: 90
  Compress: false
  Dir: /tmp/UpGo/
go:
  GoRoot: /usr/local
  GO111MODULE: 'on'
  GoProxy: https://goproxy.cn,direct
