name: Go编译和测试

on:
  push:
    branches: ["master"]

jobs:
  go-build-test:
    # 该push事件不是由其他workflow触发的，因此该作业将被执行
    runs-on: ubuntu-latest
    steps:
      - name: 'Ensure no Update UpGo Version in commit messages'
        run: |
          PR_NUMBER="${{ github.event.pull_request.number }}"
          PR_REPO="${{ github.event.pull_request.head.repo.full_name }}"
          TOKEN="${{ secrets.GITHUB_TOKEN }}"
          commits_url="https://api.github.com/repos/$PR_REPO/pulls/$PR_NUMBER/commits"
          commit_messages=$(curl -s -H "Authorization: token $TOKEN" $commits_url | jq '.[].commit.message')
          for message in $commit_messages; do
            if [[ $message == *"Update UpGo Version"* ]]; then
              echo "Found Update UpGo Version in commit message: $message"
              exit 1
            fi
          done
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.4

      - name: Go build
        run: go build -v ./...

      - name: Go test
        run: go test -v ./...
