name: Go编译和测试

on:
  push:
    branches: [ "master" ]

jobs:

  go-build-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        # Required due to the way Git works, without it this action won't be able to find any or the correct tags
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.20.4

    - name: Go build
      run: go build -v ./...

    - name: Go test
      run: go test -v ./...
  update-UpGo-version:
    needs: go-build-test
    runs-on: ubuntu-latest
    steps:
      - name: Get latest tag
        id: get-tag
        run: |
          echo "当前文件夹是："
          pwd
          echo "当前所有Git tag标签值："
          git tag -l
          # 检查是否存在标签
          if [[ -z $(git tag -l) ]]; then
            echo "No tags found."
            echo "TAG=::" >> $GITHUB_ENV
          else
            # 获取最新的标签
            latest_tag=$(git describe --tags $(git rev-list --tags --max-count=1))
            echo "TAG=$latest_tag" >> $GITHUB_ENV
          fi
      # 第三步：引用第三方workflow更新yml配置文件并提交修改后的代码
      - name: 更新 config.yml
        uses: fjogeleit/yaml-update-action@main
        with:
          branch: master
          targetBranch: master
          description: Test GitHub Action
          message: '修改config.yml文件，更新UpGo版本号' 
          title: 'Version Updates'
          token: ${{ secrets.ACCESS_TOKEN }}
          valueFile: 'conf/config.yml'
          propertyPath: 'app.version'
          value: ${{ env.TAG }}
          commitChange: true