name: Go编译和测试

on:
  push:
    branches: [ "master" ]

jobs:

  go-build-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.20.4

    - name: Go build
      run: go build -v ./...

    - name: Go test
      run: go test -v ./...