name: 发布
on:
  create:
    tags:
    - v*

jobs:
  update-file-version:
    runs-on: ubuntu-latest
    steps:
      # 第一步：切换到github目录下面
      - name: "Checkout代码"
        uses: actions/checkout@v3
        # with:
          # Required due to the way Git works, without it this action won't be able to find any or the correct tags
          # fetch-depth: 0
      # 第二步：获取当前最新tag标签值
      - name: Get latest tag
        id: get-tag
        run: |
          echo "当前文件夹是："
          pwd
          echo "当前所有Git tag标签值："
          git tag -l
          # 检查是否存在标签
          if [[ -z $(git tag -l) ]]; then
            echo "No tags found."
            echo "TAG=::" >> $GITHUB_ENV
          else
            # 获取最新的标签
            latest_tag=$(git describe --tags $(git rev-list --tags --max-count=1))
            echo "TAG=$latest_tag" >> $GITHUB_ENV
          fi
      # 第三步：更新yml配置文件并提交修改后的代码
      - name: 更新 config.yml
        uses: fjogeleit/yaml-update-action@main
        with:
          branch: master
          targetBranch: master
          description: Test GitHub Action
          message: 'Update UpGo Version' 
          title: 'Version Updates'
          token: ${{ secrets.ACCESS_TOKEN }}
          valueFile: 'conf/config.yml'
          propertyPath: 'app.version'
          value: ${{ env.TAG }}
          commitChange: true
  release:
    needs: update-file-version
    name: Release on GitHub
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Validates GO releaser config
      uses: docker://goreleaser/goreleaser:latest
      with:
        args: check

    - name: Create release on GitHub
      uses: docker://goreleaser/goreleaser:latest
      with:
        args: release
      env:
        GITHUB_TOKEN: ${{secrets.ACCESS_TOKEN}}
